# Generated by Django 5.0.6 on 2024-07-20 12:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDetails',
            fields=[
                ('problem_statment', models.CharField(max_length=350)),
                ('proposed_solution', models.TextField()),
                ('market', models.TextField()),
                ('project_image', models.ImageField(upload_to='project_images/')),
                ('competition', models.TextField()),
                ('Why_you', models.TextField()),
                ('financing', models.TextField()),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.project')),
            ],
        ),
    ]
