# Generated by Django 5.0.6 on 2024-07-20 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_projectdetails_projectdetail_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectdetail',
            old_name='project_image',
            new_name='statistical_image',
        ),
    ]
