# Generated by Django 5.0.6 on 2024-07-20 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_project_image_projectdetail_statistical_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdetail',
            name='Why_you',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='competition',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='financing',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='market',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='problem_statment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='proposed_solution',
            field=models.TextField(blank=True, null=True),
        ),
    ]
