# Generated by Django 5.0.6 on 2024-07-23 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_projectdetail_why_you_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='profiles/user-default.png', null=True, upload_to='CampusCrowd/profiles/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_image',
            field=models.ImageField(upload_to='CampusCrowd/project_images/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_short_demo_video',
            field=models.FileField(blank=True, null=True, upload_to='CampusCrowd/project_videos/'),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='statistical_image',
            field=models.ImageField(upload_to='CampusCrowd/project_images/'),
        ),
    ]
