# Generated by Django 5.0.6 on 2024-07-23 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CHAT_ROOM', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, max_length=400, null=True, upload_to='CampusCrowd/message_images/'),
        ),
    ]
