# Generated by Django 5.0.6 on 2024-07-24 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CampusCrowd', '0002_suggestions'),
        ('users', '0006_alter_profile_profile_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestions',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.project'),
        ),
    ]
